# Generated by Django 4.2.1 on 2023-06-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
