# Generated by Django 4.2.1 on 2023-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='user-default.jpg', null=True, upload_to=''),
        ),
    ]
