# Generated by Django 4.2.1 on 2023-06-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_team_coach_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founded_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='venue',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
