# Generated by Django 4.2.1 on 2023-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
