# Generated by Django 4.2.1 on 2023-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='short_number',
            field=models.IntegerField(null=True),
        ),
    ]
