# Generated by Django 4.2.1 on 2023-08-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_player_short_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='short_number',
            new_name='shirt_number',
        ),
    ]
