# Generated by Django 4.2.1 on 2023-08-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_short_number_player_shirt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='season_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(db_column='team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='myapp.team'),
        ),
    ]
