# Generated by Django 4.2.1 on 2023-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_player_last_updated_at_alter_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_highlight',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
