# Generated by Django 4.2.1 on 2023-08-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_post_is_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('minute', models.IntegerField(null=True)),
                ('injuryTime', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('home_score', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
                ('assist_player', models.ForeignKey(db_column='assist_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='assist_player_goals', to='myapp.player')),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_goals', to='myapp.match')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='player_goals', to='myapp.player')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_goals', to='myapp.team')),
            ],
            options={
                'db_table': 'goals',
            },
        ),
    ]
