# Generated by Django 4.2.1 on 2023-08-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_post_is_highlight_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='assist_player',
            field=models.ForeignKey(db_column='assist_player_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist_player_goals', to='myapp.player'),
        ),
    ]
