# Generated by Django 4.2.1 on 2023-08-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_goal_assist_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='injuryTime',
            new_name='additional_time',
        ),
    ]
