# Generated by Django 4.2.1 on 2023-08-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_player_is_national_player_national_shirt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crest_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='season_id',
            field=models.IntegerField(null=True),
        ),
    ]
