# Generated by Django 4.2.1 on 2023-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_team_tla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='season_id',
            field=models.IntegerField(null=True),
        ),
    ]
