# Generated by Django 4.2.1 on 2023-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_match_competition_id_alter_match_matchday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='national_team_id',
            field=models.IntegerField(null=True),
        ),
    ]
