# Generated by Django 4.2.1 on 2023-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_match_is_national_player_national_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_valid',
            field=models.IntegerField(default=True),
        ),
    ]
