# Generated by Django 4.2.1 on 2023-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_goal_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
