# Generated by Django 4.2.1 on 2023-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_team_tla'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='competition_id',
            field=models.IntegerField(null=True),
        ),
    ]
