# Generated by Django 4.2.1 on 2023-09-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_player_competition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('stage', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('group', models.CharField(default=1, max_length=255, null=True)),
                ('position', models.IntegerField()),
                ('played_matches', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('form', models.CharField(max_length=255, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_standings', to='myapp.team')),
            ],
            options={
                'db_table': 'standings',
                'unique_together': {('competition_id', 'season_id', 'stage', 'group', 'position')},
            },
        ),
    ]
