# Generated by Django 4.2.1 on 2023-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_standing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('competition_id', 'season_id', 'stage', 'group', 'position', 'team')},
        ),
        migrations.AddField(
            model_name='standing',
            name='season_year',
            field=models.IntegerField(null=True),
        ),
    ]
