# Generated by Django 4.2.1 on 2023-09-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_standing_unique_together_standing_season_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('competition_id', 'season_year', 'stage', 'group', 'position', 'team')},
        ),
    ]
