# Generated by Django 4.2.1 on 2023-09-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_standing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('competition_id', 'season_id', 'stage', 'group', 'position', 'team')},
        ),
    ]
