# Generated by Django 4.2.1 on 2023-09-10 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_match_season_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_updated_at',
            new_name='api_updated_at',
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
