# Generated by Django 4.2.1 on 2023-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_goal_additional_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='crest_badge_image',
        ),
        migrations.AddField(
            model_name='team',
            name='badge_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='crest_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
