# Generated by Django 4.2.1 on 2023-09-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_team_crest_badge_image_team_badge_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='badge_image',
            new_name='badge_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='crest_image',
            new_name='crest_name',
        ),
    ]
