# Generated by Django 4.2.1 on 2023-09-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_team_area_id_alter_team_competition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(db_column='away_team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='myapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(db_column='home_team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='myapp.team'),
        ),
    ]
