# Generated by Django 4.2.1 on 2023-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_match_group_match_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_national',
            field=models.BooleanField(default=False),
        ),
    ]
