# Generated by Django 4.2.1 on 2023-09-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_team_is_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
