# Generated by Django 4.2.1 on 2023-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_team_short_name_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='highlight_video_url',
            field=models.URLField(null=True),
        ),
    ]
