# Generated by Django 4.2.1 on 2023-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_match_highlight_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_stadium',
            field=models.BooleanField(default=False),
        ),
    ]
