# Generated by Django 4.2.1 on 2023-07-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_team_founded_year_alter_team_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='media/user-default', null=True, upload_to=''),
        ),
    ]
